
" Author: Cornelius


VIMRUNTIME=~/.vim

install:
		cp vimlib/plugin/hypergit.vim  $(VIMRUNTIME)/plugin/hypergit.vim

link:
		ln -s `pwd`/vimlib/plugin/hypergit.vim $(VIMRUNTIME)/plugin/hypergit.vim
